### ISSUE TITLE
Implementar método para fazer a reserva de uma sala

### ISSUE THREAD

**Issue by MYonemoto** [marcocmm/sistemaBibliotecaUTFPR#45]
O método deve chamar o método de autenticação, construir o objeto ReservaPO com os parâmetros necessários e chamar o método de persistência dos dados.

método: reservarSala
classe: SalaBO

**Comment by rmeloca** [comment]
1. Mover autenticação do do estudante no MB para uma camada abaixo
2. Mover reserva de sala de BO para salaBO

**Comment by rmeloca** [comment]
Criar enum para erros
