### ISSUE TITLE
Persistir os dados da reserva no BD

### ISSUE THREAD

**Issue by lpbaiser** [marcocmm/sistemaBibliotecaUTFPR#5]
Criar a Query de inserção, se DAOGenerico.create() não for suficiente.

**Comment by rmeloca** [comment]
Alterei algumas coisas no BD @MYonemoto, faça funcionar com a versão que tem no seu PC e comite pra depois vermos se minhas alterações sincronizam com as suas.
@lpbaiser @marcocmm  @MateusVT Fiquem avisados que não é pra sobrescrever as entidades e que não testei as minhas alterações, não se aflijam.
