### ISSUE TITLE
Implementar método para exibir as salas disponíveis

### ISSUE THREAD

**Issue by lpbaiser** [marcocmm/sistemaBibliotecaUTFPR#58]
As salas disponíveis devem serem exibidas em um campo select<html>

método: viewSalasDisponiveis
classe: ReservaMB

**Comment by rmeloca** [comment]
@marcocmm @MYonemoto 
o calendário atualiza a dataInicial da reserva
o botão de horário **deve** atualizar novamente a dataInicial da reserva
eu obtenho a lista de salas disponíveis com base na dataInicial da reserva
Será o passo 2 do wizard ou vocês pensam em fazer diferente?
