### ISSUE TITLE
Fazer as alterações necessárias para que o css dos botões seja alterado conforme a disponibilidade da sala no xhtml

### ISSUE THREAD

**Issue by lpbaiser** [marcocmm/sistemaBibliotecaUTFPR#62]
Os botões devem ter seu css atualizados conforme o retorno do método SalaBO.getStatusDaSala chamado no método updateBotoesAtivosPorDia

**Comment by marcocmm** [comment]
Marco e @MYonemoto

**Comment by rmeloca** [comment]
Regra de negócio e DAO preparados para esta etapa
